### PR TITLE
update to zabbix 3.x

### PR DESCRIPTION
**Pull request by hamsterksu**
update headers to zabbix 3.x

### CODE REVIEW

**Comment by cavaliercoder** [comment]
Thanks for raising this.

Zabbix v3 broke module API compatibility with v2. They're currently working to resolve this in [ZBX-10428](https://support.zabbix.com/browse/ZBX-10428). 

If I accept your pull request, unfortunately this module will no longer work with Zabbix v2. I'm stuck for ideas in the mean time, but can you think of any way we could publish this package with v2 and v3 compatibility?

**Comment by hamsterksu** [comment]
Hi @cavaliercoder, 
i see 2 possible ways how to solve version issue
1. add some ifdef to header files. but i don't like this way. 
2. create 2 different branches(v2.x, v3.x) in project and use http://gopkg.in to resolve versions. seems it's very easy solution and very popular in golang world

**Comment by cavaliercoder** [comment]
Cool I like that second option. I'll organise that, accept your PR and update documentation in the next few days.

**Comment by cavaliercoder** [comment]
I've created gopkg.in links and merged your PR into the v3 branch. README has been updated with install instructions for v3.

Thanks very much for this :)

**Pull request closed without merging**
